//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itbeard.Shortener {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizations {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Itbeard.Shortener.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Index_Header {
            get {
                return ResourceManager.GetString("Index_Header", resourceCulture);
            }
        }
        
        internal static string SelectSiteLanguage {
            get {
                return ResourceManager.GetString("SelectSiteLanguage", resourceCulture);
            }
        }
        
        internal static string Nav_Logout {
            get {
                return ResourceManager.GetString("Nav_Logout", resourceCulture);
            }
        }
        
        internal static string Nav_ToIndex {
            get {
                return ResourceManager.GetString("Nav_ToIndex", resourceCulture);
            }
        }
        
        internal static string ConfirmJS_DeleteLink {
            get {
                return ResourceManager.GetString("ConfirmJS_DeleteLink", resourceCulture);
            }
        }
        
        internal static string Index_ShortenLink {
            get {
                return ResourceManager.GetString("Index_ShortenLink", resourceCulture);
            }
        }
        
        internal static string Index_TableHead_Created {
            get {
                return ResourceManager.GetString("Index_TableHead_Created", resourceCulture);
            }
        }
        
        internal static string Index_TableHead_ShortName {
            get {
                return ResourceManager.GetString("Index_TableHead_ShortName", resourceCulture);
            }
        }
        
        internal static string Index_TableHead_Clicks {
            get {
                return ResourceManager.GetString("Index_TableHead_Clicks", resourceCulture);
            }
        }
        
        internal static string Index_TableHead_TargetUrl {
            get {
                return ResourceManager.GetString("Index_TableHead_TargetUrl", resourceCulture);
            }
        }
        
        internal static string Index_TableButtons_Edit {
            get {
                return ResourceManager.GetString("Index_TableButtons_Edit", resourceCulture);
            }
        }
        
        internal static string Index_TableButtons_Delete {
            get {
                return ResourceManager.GetString("Index_TableButtons_Delete", resourceCulture);
            }
        }
        
        internal static string ReduceLink_Header {
            get {
                return ResourceManager.GetString("ReduceLink_Header", resourceCulture);
            }
        }
        
        internal static string ReduceLink_TargetUrl {
            get {
                return ResourceManager.GetString("ReduceLink_TargetUrl", resourceCulture);
            }
        }
        
        internal static string ReduceLink_TargetUrlPlaceholder {
            get {
                return ResourceManager.GetString("ReduceLink_TargetUrlPlaceholder", resourceCulture);
            }
        }
        
        internal static string ReduceLink_ShortName {
            get {
                return ResourceManager.GetString("ReduceLink_ShortName", resourceCulture);
            }
        }
        
        internal static string ReduceLink_ShortNamePlaceholder {
            get {
                return ResourceManager.GetString("ReduceLink_ShortNamePlaceholder", resourceCulture);
            }
        }
        
        internal static string ReduceLink_ShortNameNote {
            get {
                return ResourceManager.GetString("ReduceLink_ShortNameNote", resourceCulture);
            }
        }
        
        internal static string ReduceLink_CreateButton {
            get {
                return ResourceManager.GetString("ReduceLink_CreateButton", resourceCulture);
            }
        }
        
        internal static string ReduceLink_ResultLink {
            get {
                return ResourceManager.GetString("ReduceLink_ResultLink", resourceCulture);
            }
        }
        
        internal static string ReduceLink_Copy {
            get {
                return ResourceManager.GetString("ReduceLink_Copy", resourceCulture);
            }
        }
        
        internal static string ReduceLink_Exception_LongShortName {
            get {
                return ResourceManager.GetString("ReduceLink_Exception_LongShortName", resourceCulture);
            }
        }
        
        internal static string ReduceLink_Exception_TargetUrlEmpty {
            get {
                return ResourceManager.GetString("ReduceLink_Exception_TargetUrlEmpty", resourceCulture);
            }
        }
        
        internal static string ReduceLink_Exception_DuplicateShortUrl {
            get {
                return ResourceManager.GetString("ReduceLink_Exception_DuplicateShortUrl", resourceCulture);
            }
        }
        
        internal static string EditLink_Header {
            get {
                return ResourceManager.GetString("EditLink_Header", resourceCulture);
            }
        }
        
        internal static string EditLink_TargetUrl {
            get {
                return ResourceManager.GetString("EditLink_TargetUrl", resourceCulture);
            }
        }
        
        internal static string EditLink_TargetUrlPlaceholder {
            get {
                return ResourceManager.GetString("EditLink_TargetUrlPlaceholder", resourceCulture);
            }
        }
        
        internal static string EditLink_ShortName {
            get {
                return ResourceManager.GetString("EditLink_ShortName", resourceCulture);
            }
        }
        
        internal static string EditLink_ShortNameNote {
            get {
                return ResourceManager.GetString("EditLink_ShortNameNote", resourceCulture);
            }
        }
        
        internal static string EditLink_SaveButton {
            get {
                return ResourceManager.GetString("EditLink_SaveButton", resourceCulture);
            }
        }
        
        internal static string EditLink_Exception_TargetUrlEmpty {
            get {
                return ResourceManager.GetString("EditLink_Exception_TargetUrlEmpty", resourceCulture);
            }
        }
        
        internal static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        internal static string Redirector_RedirectMessagge {
            get {
                return ResourceManager.GetString("Redirector_RedirectMessagge", resourceCulture);
            }
        }
        
        internal static string Redirector_UrlNotFound {
            get {
                return ResourceManager.GetString("Redirector_UrlNotFound", resourceCulture);
            }
        }
        
        internal static string App_RestoreSession {
            get {
                return ResourceManager.GetString("App_RestoreSession", resourceCulture);
            }
        }
        
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        internal static string App_Description {
            get {
                return ResourceManager.GetString("App_Description", resourceCulture);
            }
        }
        
        internal static string App_PageNotFound {
            get {
                return ResourceManager.GetString("App_PageNotFound", resourceCulture);
            }
        }
        
        internal static string App_LoginButton {
            get {
                return ResourceManager.GetString("App_LoginButton", resourceCulture);
            }
        }
        
        internal static string Host_PageTitle {
            get {
                return ResourceManager.GetString("Host_PageTitle", resourceCulture);
            }
        }
        
        internal static string Host_Exception_Prod {
            get {
                return ResourceManager.GetString("Host_Exception_Prod", resourceCulture);
            }
        }
        
        internal static string Host_Exception_Dev {
            get {
                return ResourceManager.GetString("Host_Exception_Dev", resourceCulture);
            }
        }
        
        internal static string AdditionPageTitle {
            get {
                return ResourceManager.GetString("AdditionPageTitle", resourceCulture);
            }
        }
        
        internal static string Index_PageTitle {
            get {
                return ResourceManager.GetString("Index_PageTitle", resourceCulture);
            }
        }
        
        internal static string EditLink_PageTitle {
            get {
                return ResourceManager.GetString("EditLink_PageTitle", resourceCulture);
            }
        }
        
        internal static string ReduceLink_PageTitle {
            get {
                return ResourceManager.GetString("ReduceLink_PageTitle", resourceCulture);
            }
        }
    }
}
